framework:
    secret: '%env(APP_SECRET)%'
    default_locale: '%locale%'
    #csrf_protection: true
    #http_method_override: true

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session: false
        #handler_id: ~
        #cookie_secure: auto
        #cookie_samesite: lax

    assets:
        json_manifest_path: '%kernel.project_dir%/public/assets/manifest.json'
        #base_urls:
        #    - '%router.request_context.scheme%://%router.request_context.host%'

    #esi: true
    #fragments: true
    php_errors:
        log: true
