stenope:
  shared_html_crawlers: true
  providers:
    App\Model\Article: '%kernel.project_dir%/content/article'
    App\Model\Game: '%kernel.project_dir%/content/game'
    App\Model\Talk: '%kernel.project_dir%/content/talk'
    App\Model\Tool: '%kernel.project_dir%/content/tool'
