# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'en'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    Symfony\Component\Serializer\Encoder\YamlEncoder: ~

    Content\:
        resource: '../content/*'
        #exclude: '../content/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    Content\ContentManager:
        #$normalizers: []
        arguments:
            $path: '%kernel.project_dir%/data'
            $decoders:
                - '@Symfony\Component\Serializer\Encoder\YamlEncoder'
                - '@Content\Decoder\MarkdownDecoder'
                - '@Content\Decoder\HtmlDecoder'
        calls:
            # Content Providers
            - { method: 'addProvider', arguments: ['@App\Provider\ArticleProvider'] }
            # Property Handlers
            - { method: 'addPropertyHandler', arguments: ['date', '@Content\PropertyHandler\DateTimePropertyHandler'] }
            - { method: 'addPropertyHandler', arguments: ['lastModified', '@Content\PropertyHandler\LastModifiedPropertyHandler'] }
            - { method: 'addPropertyHandler', arguments: ['slug', '@Content\PropertyHandler\SlugPropertyHandler'] }

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']
